import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import TrpcProvider from "@/trpc/Provider";
import ClientProviders from "./ClientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
	modals: React.ReactNode;
}
export default function RootLayout({ children, modals }: RootLayoutProps) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-background w-full h-full min-h-screen overscroll-none`}>
				<ClientProviders>
					<TrpcProvider>
						<div>{children}</div>
						<div>{modals}</div>
					</TrpcProvider>
				</ClientProviders>
			</body>
		</html>
	);
}
