import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import TrpcProvider from "@/trpc/Provider";
import MotionProvider from "@/components/wrappers/FramerMotion/MotionProvider";
import ClientProviders from "./ClientProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-slate-100 w-full h-full min-h-screen overscroll-none`}>
				<ClientProviders>
					<TrpcProvider>
						<MotionProvider>{children}</MotionProvider>
					</TrpcProvider>
				</ClientProviders>
			</body>
		</html>
	);
}
